<?php

namespace Database\Seeders;

use App\Models\Neighbour;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class NeighbourSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        $neighbours = [
            ['name' => 'Nakhlat Deira', 'local_name' => 'نخلة ديرة', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Nakhlat Deira', 'local_name' => 'نخلة ديرة', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Corniche', 'local_name' => 'الكورنيش', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Ras', 'local_name' => 'الراس', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Dhagaya', 'local_name' => 'الضغاية', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Buteen', 'local_name' => 'البطين', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Sabkha', 'local_name' => 'السبخة', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Ayal Nasir', 'local_name' => 'عيال ناصر', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Murar', 'local_name' => 'المرر', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Naif', 'local_name' => 'نايف', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Rigga', 'local_name' => 'الرقة', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Corniche Deira', 'local_name' => 'كورنيش ديرة', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Baraha', 'local_name' => 'البراحة', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Muteena', 'local_name' => 'المطينة', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Muraqqabat', 'local_name' => 'المرقبات', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Rigga Al Buteen', 'local_name' => 'رقة البطين', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Abu Hail', 'local_name' => 'أبو هيل', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Hor Al Anz', 'local_name' => 'هورالعنز', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Khabisi', 'local_name' => 'الخبيصي', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Port Saeed', 'local_name' => 'بور سعيد', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Hamriya Port', 'local_name' => 'ميناء الحمرية', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Waheda', 'local_name' => 'الوحيدة', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Hor Al Anz East', 'local_name' => 'هور العنز شرق', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Mamzar', 'local_name' => 'الممزر', 'district_id' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Nad Shamma', 'local_name' => 'ند شما', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Garhoud', 'local_name' => 'القرهود', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Umm Ramool', 'local_name' => 'أم رمول', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Rashidiya', 'local_name' => 'الراشدية', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Dubai Airport', 'local_name' => 'مطار دبي الدولي', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Twar First', 'local_name' => 'الطوار الأولى', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Twar Second', 'local_name' => 'الطوار الثانية', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Twar Third', 'local_name' => 'الطوار الثالثة', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Nahda First', 'local_name' => 'النهدة الأولى', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Qusais First', 'local_name' => 'القصيص الأولى', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Qusais Second', 'local_name' => 'القصيص الثانية', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Twar Fourth', 'local_name' => 'الطوار الرابعة', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Nahda Second', 'local_name' => 'النهدة الثانية', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Qusais Industrial First', 'local_name' => 'القصيص الصناعية الأولى', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Qusais Industrial Second', 'local_name' => 'القصيص الصناعية الثانية', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Muhaisnah Third', 'local_name' => 'محيصنة الثالثة', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Muhaisnah Fourth', 'local_name' => 'محيصنة الرابعة', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Qusais Industrial Third', 'local_name' => 'القصيص الصناعية الثالثة', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Qusais Industrial Fourth', 'local_name' => 'القصيص الصناعية الرابعة', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Qusais Industrial Fifth', 'local_name' => 'القصيص الصناعية الخامسة', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Mirdif', 'local_name' => 'مردف', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Mushrif', 'local_name' => 'مشرف', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Muhaisnah First', 'local_name' => 'محيصنة الأولى', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Mizhar First', 'local_name' => 'المزهر الأولى', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Mizhar Second', 'local_name' => 'المزهر الثانية', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Muhaisnah Second', 'local_name' => 'محيصنة الثانية', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Oud Al Muteena First', 'local_name' => 'عود المطينة الأولى', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Mizhar Third', 'local_name' => 'المزهر الثالثة', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Muhaisnah Fifth', 'local_name' => 'محصينة الخامسة', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Oud Al Muteena Second', 'local_name' => 'عود المطينة الثانية', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Wadi Alamardi', 'local_name' => 'وادي العمردي', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Khawaneej One', 'local_name' => 'الخوانيج الأولى', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Khawaneej Two', 'local_name' => 'الخوانيج الثانية', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Ayas', 'local_name' => 'العياص', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Ttay', 'local_name' => 'الطي', 'district_id' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Jumeirah Bay', 'local_name' => 'شاطئ جميرا', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'World Islands', 'local_name' => 'جزر العالم', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Jumeirah Island 2', 'local_name' => 'جزيرة جميرا 2', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Shindagha', 'local_name' => 'الشندغة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Souk Al Kabir', 'local_name' => 'السوق الكبير', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Hamriya', 'local_name' => 'الحمرية', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Umm Hurair First', 'local_name' => 'أم هرير الأولى', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Umm Hurair Second', 'local_name' => 'أم هرير الأولى', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Rifa', 'local_name' => 'الرفاعة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Mankhool', 'local_name' => 'المنخول', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Karama', 'local_name' => 'الكرامة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Oud Metha', 'local_name' => 'عود ميثاء', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Dubai Maritime City (Al Mina)', 'local_name' => 'مدينة دبي المالحية', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Hudaiba', 'local_name' => 'الحضيبة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Jafiliya', 'local_name' => 'الجافلية', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Kifaf', 'local_name' => 'الكفاف', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Zabeel First', 'local_name' => 'زعبيل الأولى', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Jaddaf', 'local_name' => 'الجداف', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Jumeirah First', 'local_name' => 'جميرا الأولى', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Bada', 'local_name' => 'البدع', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Satwa', 'local_name' => 'السطوة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Trade Centre 1', 'local_name' => 'المركز التجاري الأولى', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Trade Centre 2', 'local_name' => 'المركز التجاري الثانية', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Zabeel Second', 'local_name' => 'زعبيل الثانية', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Jumeirah Second', 'local_name' => 'جميرا الثانية', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Wasl', 'local_name' => 'الوصل', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Downtown Dubai', 'local_name' => 'برج خليفة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Kalij Al Tejari (Business Bay)', 'local_name' => 'الخليج التجاري', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Markada', 'local_name' => 'المركاض', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Jumeirah Third', 'local_name' => 'جميرا الثالثة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Safa First', 'local_name' => 'الصفا الأولى', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Quoz First', 'local_name' => 'القوز الاولى', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Ghadeer Al Tair', 'local_name' => 'غدير الطير', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Umm Suqeim First', 'local_name' => 'أم سقيم الأولى', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Safa Second', 'local_name' => 'الصفا الثانية', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Quoz Third', 'local_name' => 'القوز الثالثة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Quoz Fourth', 'local_name' => 'القوز الرابعة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Umm Suqeim Second', 'local_name' => 'أم سقيم الثانية', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Manara', 'local_name' => 'المنارة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Quoz Industrial First', 'local_name' => 'القوز الصناعية الأولى', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Quoz Industrial Second', 'local_name' => 'القوز الصناعية الثانية', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Umm Suqeim Third', 'local_name' => 'أم سقيم الثالثة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Umm Al Sheif', 'local_name' => 'أم الشيف', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Quoz Industrial Third', 'local_name' => 'القوز الصناعية الثالثة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Quoz Industrial Fourth', 'local_name' => 'القوز الصناعية الرابعة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Sufouh First', 'local_name' => 'الصفوح الأولى', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Barsha First', 'local_name' => 'البرشاء الأولى', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Barsha Third', 'local_name' => 'البرشاء الثالثة', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Barsha Second', 'local_name' => 'البرشاء الثانية', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Palm Jumeirah', 'local_name' => 'نخلة جميرا', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Sufouh Second', 'local_name' => 'الصفوح الثانية', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Thanyah First', 'local_name' => 'الثنيه الأولى (قرية ربيع الصحراء)', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Thanyah Second', 'local_name' => 'الثنيه الثانية (مضمار جبل علي)', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Thanyah Third', 'local_name' => 'الثنيه الثالثة (تلال الامارات الثانية)', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Dubai Marina', 'local_name' => 'مرسى دبي', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Thanyah Fifth', 'local_name' => 'الثنيه الخامسة (تلال الامارات الاولى)', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Thanyah Fourth', 'local_name' => 'الثنيه الرابعة (تلال الامارات الثالثة)', 'district_id' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Kheeran', 'local_name' => 'الخيران', 'district_id' => 4, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Ras Al Khor', 'local_name' => 'رأس الخور', 'district_id' => 4, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Khairan First', 'local_name' => 'الخيران الأولى', 'district_id' => 4, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Nad Al Hammar', 'local_name' => 'ند الحمر', 'district_id' => 4, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Warqaa First', 'local_name' => 'الورقاء الأولى', 'district_id' => 4, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Warqaa Second', 'local_name' => 'الورقاء الثانية', 'district_id' => 4, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Warqaa Third', 'local_name' => 'الورقاء الثالثة', 'district_id' => 4, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Warqaa Fourth', 'local_name' => 'الورقاء الرابعة', 'district_id' => 4, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Warqaa Fifth', 'local_name' => 'الورقاء الخامسة', 'district_id' => 4, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Athbah', 'local_name' => 'العذبة', 'district_id' => 4, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Palm Jebel Ali', 'local_name' => 'نخلة جبل علي', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Wajeha Al Bahriah', 'local_name' => 'الواجهة البحرية', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Hessyan First', 'local_name' => 'حصيان الاولى', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Hessyan Second', 'local_name' => 'حصيان الثانية', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Saih Shuaib 1', 'local_name' => 'سيح شعيب 1', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Jebel Ali Industrial Third', 'local_name' => 'جبل علي الصناعية الثالثة', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Jebel Ali Industrial Second', 'local_name' => 'جبل علي الصناعية الثانية', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Madinat Al Mataar', 'local_name' => 'مدينة المطار', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Saih Shuaib 2', 'local_name' => 'سيح شعيب 2', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Saih Shuaib 3', 'local_name' => 'سيح شعيب 3', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Saih Shuaib 4', 'local_name' => 'سيح شعيب 4', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Jebel Ali First', 'local_name' => 'جبل علي الأولى', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Jebel Ali Second', 'local_name' => 'جبل علي الثانية', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Jebel Ali Third', 'local_name' => 'جبل علي الثالثة', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Mena Jebel Ali', 'local_name' => 'ميناء جبل علي', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Dubai Investment Park Second', 'local_name' => 'مجمع دبي للاستثمار الثاني', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Dubai Investment Park First', 'local_name' => 'مجمع دبي للاستثمار الأول', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Jebel Ali Industrial First', 'local_name' => 'جبل علي الصناعية الأولى', 'district_id' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Bu Kadra', 'local_name' => 'بو كدرة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Ras Al Khor Industrial First', 'local_name' => 'رأس الخور الصناعية الأولى', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Ras Al Khor Industrial Second', 'local_name' => 'رأس الخور الصناعية الثانية', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Ras Al Khor Industrial Third', 'local_name' => 'رأس الخور الصناعية الثالثة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Nad Al Sheba Second', 'local_name' => 'ند الشبا الثانية', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Nad Al Sheba Third', 'local_name' => 'ند الشبا الثالثة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Nad Al Sheba Fourth', 'local_name' => 'ند الشبا الرابعة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Nad Al Sheba First', 'local_name' => 'ند الشبا الأولى', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Warsan First', 'local_name' => 'ورسان الاولى', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Warsan Second', 'local_name' => 'ورسان الثانية', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Warsan Fourth', 'local_name' => 'ورسان الرابعة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Nad Hessa', 'local_name' => 'ند حصة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Hadaeq Sheikh Mohammed Bin Rashid', 'local_name' => 'حدائق الشيخ محمد بن راشد', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Wadi Al Safa 2', 'local_name' => 'وادي الصفا 2', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Wadi Al Safa 3', 'local_name' => 'وادي الصفا 3', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Wadi Al Safa 4', 'local_name' => 'وادي الصفا 4', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Wadi Al Safa 5', 'local_name' => 'وادي الصفا 5', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Wadi Al Safa 6', 'local_name' => 'وادي الصفا 6', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Wadi Al Safa 7', 'local_name' => 'وادي الصفا 7', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Barsha South First', 'local_name' => 'البرشاء جنوب الاولى', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Barsha South Second', 'local_name' => 'البرشاء جنوب الثانية', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Barsha South Third', 'local_name' => 'البرشاء جنوب الثالثة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Hebiah First', 'local_name' => 'الحبيه الاول', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Hebiah Second', 'local_name' => 'الحبيه الثانية', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Hebiah Third', 'local_name' => 'الحبيه الثالثة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Hebiah Sixth', 'local_name' => 'الحبيه السادسة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Barsha South Fourth', 'local_name' => 'البرشاء جنوب الرابعة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Hebiah Fourth', 'local_name' => 'الحبيه الرابعة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Hebiah Fifth', 'local_name' => 'الحبيه الخامسة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Barsha South Fifth', 'local_name' => 'البرشاء جنوب الخامسة', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Me`aisem First', 'local_name' => 'معيصم الأول', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Me`aisem Second', 'local_name' => 'معيصم الثانية', 'district_id' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Awir First', 'local_name' => 'العوير الأولى', 'district_id' => 7, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Awir Second', 'local_name' => 'العوير الثانية', 'district_id' => 7, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Enkhali', 'local_name' => 'نخلي', 'district_id' => 7, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Wohoosh', 'local_name' => 'الوحوش', 'district_id' => 7, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Lehbab First', 'local_name' => 'لهباب الأولى', 'district_id' => 7, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Meryal', 'local_name' => 'المريال', 'district_id' => 7, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Nazwah', 'local_name' => 'نزوه', 'district_id' => 7, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Warsan 3', 'local_name' => 'ورسان الثالثة', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Rowaiyah First', 'local_name' => 'الرويه الأولى', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Rowaiyah Second', 'local_name' => 'الرويه الثانية', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Rowaiyah Third', 'local_name' => 'الرويه الثالثة', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Mereiyeel', 'local_name' => 'مرييل', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Umm Al Daman', 'local_name' => 'أم الدمن', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Le Hemaira', 'local_name' => 'الحميرا', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Lehbab Second', 'local_name' => 'لهباب الثانية', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Umm Al Mo`meneen', 'local_name' => 'أم المؤمنين', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Margham', 'local_name' => 'مرغم', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Maha', 'local_name' => 'المها', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Umm Eselay', 'local_name' => 'أم السلي', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Remah', 'local_name' => 'رماح', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Margab', 'local_name' => 'مرقب', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Yaraah', 'local_name' => 'يراح', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Hatta', 'local_name' => 'حتا', 'district_id' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Madinat Hind 1', 'local_name' => 'مدينة هند 1', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Madinat Hind 2', 'local_name' => 'مدينة هند 2', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Madinat Hind 3', 'local_name' => 'مدينة هند 3', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Madinat Hind 4', 'local_name' => 'مدينة هند 4', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Yufrah 1', 'local_name' => 'اليفره 1', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Marmoom', 'local_name' => 'المرموم', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Yufrah 2', 'local_name' => 'اليفره 2', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Yalayis 1', 'local_name' => 'الياليس 1', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Yalayis 2', 'local_name' => 'الياليس 2', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Yalayis 3', 'local_name' => 'الياليس 3', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Yalayis 4', 'local_name' => 'الياليس 4', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Yalayis 5', 'local_name' => 'الياليس 5', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Lesaily', 'local_name' => 'الليسيلي', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Grayteesah', 'local_name' => 'قريطيسه', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Fagaa', 'local_name' => 'الفقع', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Saih Al Salam', 'local_name' => 'سيح السلم', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Hathmah', 'local_name' => 'الحثمة', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Madinat Latifa', 'local_name' => 'مدينة لطيفة', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Ghadeer Barashy', 'local_name' => 'غدير براشي', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Saih Al Dahal', 'local_name' => 'سيح الدحل', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al O`shoosh', 'local_name' => 'العشوش', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Saih Shua`alah', 'local_name' => 'سيح شعيله', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Mugatrah', 'local_name' => 'مقطره', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Layan 1', 'local_name' => 'الليان 1', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Al Layan 2', 'local_name' => 'الليان 2', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,],
            ['name' => 'Hefair', 'local_name' => 'حفير', 'district_id' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,]
        ];

        foreach ($neighbours as $neighbour) {
            Neighbour::create($neighbour);
        }
    }
}
