<?php

namespace Database\Seeders;

use App\Models\Neighbour;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class NeighbourSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        $neighbours = [
            ['name' => 'Nakhlat Deira', 'local_name' => 'نخلة ديرة', 'district_id' => 1, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Corniche', 'local_name' => 'الكورنيش', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Ras', 'local_name' => 'الراس', 'district_id' => 1, 'latitude' => 25.2627, 'longitude' => 55.2962, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Dhagaya', 'local_name' => 'الضغاية', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Buteen', 'local_name' => 'البطين', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Sabkha', 'local_name' => 'السبخة', 'district_id' => 1, 'latitude' => 25.2627, 'longitude' => 55.2962, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ayal Nasir', 'local_name' => 'عيال ناصر', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Murar', 'local_name' => 'المرر', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Naif', 'local_name' => 'نايف', 'district_id' => 1, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Rigga', 'local_name' => 'الرقة', 'district_id' => 1, 'latitude' => 25.2627, 'longitude' => 55.2962, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Corniche Deira', 'local_name' => 'كورنيش ديرة', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Baraha', 'local_name' => 'البراحة', 'district_id' => 1, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Muteena', 'local_name' => 'المطينة', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Muraqqabat', 'local_name' => 'المرقبات', 'district_id' => 1, 'latitude' => 25.2627, 'longitude' => 55.2962, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Rigga Al Buteen', 'local_name' => 'رقة البطين', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Abu Hail', 'local_name' => 'أبو هيل', 'district_id' => 1, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hor Al Anz', 'local_name' => 'هورالعنز', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Khabisi', 'local_name' => 'الخبيصي', 'district_id' => 1, 'latitude' => 25.2627, 'longitude' => 55.2962, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Port Saeed', 'local_name' => 'بور سعيد', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hamriya Port', 'local_name' => 'ميناء الحمرية', 'district_id' => 1, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Waheda', 'local_name' => 'الوحيدة', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hor Al Anz East', 'local_name' => 'هور العنز شرق', 'district_id' => 1, 'latitude' => 25.2627, 'longitude' => 55.2962, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Mamzar', 'local_name' => 'الممزر', 'district_id' => 1, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nad Shamma', 'local_name' => 'ند شما', 'district_id' => 2, 'latitude' => 25.2492, 'longitude' => 55.3652, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Garhoud', 'local_name' => 'القرهود', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Umm Ramool', 'local_name' => 'أم رمول', 'district_id' => 2, 'latitude' => 25.2223, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Rashidiya', 'local_name' => 'الراشدية', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dubai Airport', 'local_name' => 'مطار دبي الدولي', 'district_id' => 2, 'latitude' => 25.2532, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Twar First', 'local_name' => 'الطوار الأولى', 'district_id' => 2, 'latitude' => 25.2492, 'longitude' => 55.3652, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Twar Second', 'local_name' => 'الطوار الثانية', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Twar Third', 'local_name' => 'الطوار الثالثة', 'district_id' => 2, 'latitude' => 25.2223, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Nahda First', 'local_name' => 'النهدة الأولى', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Qusais First', 'local_name' => 'القصيص الأولى', 'district_id' => 2, 'latitude' => 25.2532, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Qusais Second', 'local_name' => 'القصيص الثانية', 'district_id' => 2, 'latitude' => 25.2492, 'longitude' => 55.3652, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Twar Fourth', 'local_name' => 'الطوار الرابعة', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Nahda Second', 'local_name' => 'النهدة الثانية', 'district_id' => 2, 'latitude' => 25.2223, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Qusais Industrial First', 'local_name' => 'القصيص الصناعية الأولى', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Qusais Industrial Second', 'local_name' => 'القصيص الصناعية الثانية', 'district_id' => 2, 'latitude' => 25.2532, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Muhaisnah Third', 'local_name' => 'محيصنة الثالثة', 'district_id' => 2, 'latitude' => 25.2492, 'longitude' => 55.3652, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Muhaisnah Fourth', 'local_name' => 'محيصنة الرابعة', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Qusais Industrial Third', 'local_name' => 'القصيص الصناعية الثالثة', 'district_id' => 2, 'latitude' => 25.2223, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Qusais Industrial Fourth', 'local_name' => 'القصيص الصناعية الرابعة', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Qusais Industrial Fifth', 'local_name' => 'القصيص الصناعية الخامسة', 'district_id' => 2, 'latitude' => 25.2532, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mirdif', 'local_name' => 'مردف', 'district_id' => 2, 'latitude' => 25.2169, 'longitude' => 55.4054, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mushrif', 'local_name' => 'مشرف', 'district_id' => 2, 'latitude' => 25.2223, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Muhaisnah First', 'local_name' => 'محيصنة الأولى', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Mizhar First', 'local_name' => 'المزهر الأولى', 'district_id' => 2, 'latitude' => 25.2532, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Mizhar Second', 'local_name' => 'المزهر الثانية', 'district_id' => 2, 'latitude' => 25.2492, 'longitude' => 55.3652, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Muhaisnah Second', 'local_name' => 'محيصنة الثانية', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Oud Al Muteena First', 'local_name' => 'عود المطينة الأولى', 'district_id' => 2, 'latitude' => 25.2223, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Mizhar Third', 'local_name' => 'المزهر الثالثة', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Muhaisnah Fifth', 'local_name' => 'محصينة الخامسة', 'district_id' => 2, 'latitude' => 25.2532, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Oud Al Muteena Second', 'local_name' => 'عود المطينة الثانية', 'district_id' => 2, 'latitude' => 25.2492, 'longitude' => 55.3652, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wadi Alamardi', 'local_name' => 'وادي العمردي', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Khawaneej One', 'local_name' => 'الخوانيج الأولى', 'district_id' => 2, 'latitude' => 25.2223, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Khawaneej Two', 'local_name' => 'الخوانيج الثانية', 'district_id' => 2, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Ayas', 'local_name' => 'العياص', 'district_id' => 2, 'latitude' => 25.2532, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Ttay', 'local_name' => 'الطي', 'district_id' => 2, 'latitude' => 25.2492, 'longitude' => 55.3652, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jumeirah Bay', 'local_name' => 'شاطئ جميرا', 'district_id' => 3, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'World Islands', 'local_name' => 'جزر العالم', 'district_id' => 3, 'latitude' => 25.2223, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jumeirah Island 2', 'local_name' => 'جزيرة جميرا 2', 'district_id' => 3, 'latitude' => 25.2385, 'longitude' => 55.3528, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Shindagha', 'local_name' => 'الشندغة', 'district_id' => 3, 'latitude' => 25.2532, 'longitude' => 55.3657, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Souk Al Kabir', 'local_name' => 'السوق الكبير', 'district_id' => 3, 'latitude' => 25.2492, 'longitude' => 55.3652, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hamriya', 'local_name' => 'الحمرية', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Umm Hurair First', 'local_name' => 'أم هرير الأولى', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Umm Hurair Second', 'local_name' => 'أم هرير الأولى', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Rifa', 'local_name' => 'الرفاعة', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Mankhool', 'local_name' => 'المنخول', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Karama', 'local_name' => 'الكرامة', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Oud Metha', 'local_name' => 'عود ميثاء', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dubai Maritime City (Al Mina)', 'local_name' => 'مدينة دبي المالحية', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hudaiba', 'local_name' => 'الحضيبة', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Jafiliya', 'local_name' => 'الجافلية', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Kifaf', 'local_name' => 'الكفاف', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Zabeel First', 'local_name' => 'زعبيل الأولى', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Jaddaf', 'local_name' => 'الجداف', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jumeirah First', 'local_name' => 'جميرا الأولى', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Bada', 'local_name' => 'البدع', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Satwa', 'local_name' => 'السطوة', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Trade Centre 1', 'local_name' => 'المركز التجاري الأولى', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Trade Centre 2', 'local_name' => 'المركز التجاري الثانية', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Zabeel Second', 'local_name' => 'زعبيل الثانية', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jumeirah Second', 'local_name' => 'جميرا الثانية', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Wasl', 'local_name' => 'الوصل', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Downtown Dubai', 'local_name' => 'برج خليفة', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Kalij Al Tejari (Business Bay)', 'local_name' => 'الخليج التجاري', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Markada', 'local_name' => 'المركاض', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jumeirah Third', 'local_name' => 'جميرا الثالثة', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Safa First', 'local_name' => 'الصفا الأولى', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Quoz First', 'local_name' => 'القوز الاولى', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ghadeer Al Tair', 'local_name' => 'غدير الطير', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Umm Suqeim First', 'local_name' => 'أم سقيم الأولى', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Safa Second', 'local_name' => 'الصفا الثانية', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Quoz Third', 'local_name' => 'القوز الثالثة', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Quoz Fourth', 'local_name' => 'القوز الرابعة', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Umm Suqeim Second', 'local_name' => 'أم سقيم الثانية', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Manara', 'local_name' => 'المنارة', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Quoz Industrial First', 'local_name' => 'القوز الصناعية الأولى', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Quoz Industrial Second', 'local_name' => 'القوز الصناعية الثانية', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Umm Suqeim Third', 'local_name' => 'أم سقيم الثالثة', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Umm Al Sheif', 'local_name' => 'أم الشيف', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Quoz Industrial Third', 'local_name' => 'القوز الصناعية الثالثة', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Quoz Industrial Fourth', 'local_name' => 'القوز الصناعية الرابعة', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Sufouh First', 'local_name' => 'الصفوح الأولى', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Barsha First', 'local_name' => 'البرشاء الأولى', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Barsha Third', 'local_name' => 'البرشاء الثالثة', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Barsha Second', 'local_name' => 'البرشاء الثانية', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Palm Jumeirah', 'local_name' => 'نخلة جميرا', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Sufouh Second', 'local_name' => 'الصفوح الثانية', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Thanyah First', 'local_name' => 'الثنيه الأولى (قرية ربيع الصحراء)', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Thanyah Second', 'local_name' => 'الثنيه الثانية (مضمار جبل علي)', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Thanyah Third', 'local_name' => 'الثنيه الثالثة (تلال الامارات الثانية)', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dubai Marina', 'local_name' => 'مرسى دبي', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Thanyah Fifth', 'local_name' => 'الثنيه الخامسة (تلال الامارات الاولى)', 'district_id' => 3, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Thanyah Fourth', 'local_name' => 'الثنيه الرابعة (تلال الامارات الثالثة)', 'district_id' => 3, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Kheeran', 'local_name' => 'الخيران', 'district_id' => 4, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ras Al Khor', 'local_name' => 'رأس الخور', 'district_id' => 4, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Khairan First', 'local_name' => 'الخيران الأولى', 'district_id' => 4, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nad Al Hammar', 'local_name' => 'ند الحمر', 'district_id' => 4, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Warqaa First', 'local_name' => 'الورقاء الأولى', 'district_id' => 4, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Warqaa Second', 'local_name' => 'الورقاء الثانية', 'district_id' => 4, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Warqaa Third', 'local_name' => 'الورقاء الثالثة', 'district_id' => 4, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Warqaa Fourth', 'local_name' => 'الورقاء الرابعة', 'district_id' => 4, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Warqaa Fifth', 'local_name' => 'الورقاء الخامسة', 'district_id' => 4, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Athbah', 'local_name' => 'العذبة', 'district_id' => 4, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Palm Jebel Ali', 'local_name' => 'نخلة جبل علي', 'district_id' => 5, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Wajeha Al Bahriah', 'local_name' => 'الواجهة البحرية', 'district_id' => 5, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hessyan First', 'local_name' => 'حصيان الاولى', 'district_id' => 5, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hessyan Second', 'local_name' => 'حصيان الثانية', 'district_id' => 5, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saih Shuaib 1', 'local_name' => 'سيح شعيب 1', 'district_id' => 5, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jebel Ali Industrial Third', 'local_name' => 'جبل علي الصناعية الثالثة', 'district_id' => 5, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jebel Ali Industrial Second', 'local_name' => 'جبل علي الصناعية الثانية', 'district_id' => 5, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Madinat Al Mataar', 'local_name' => 'مدينة المطار', 'district_id' => 5, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saih Shuaib 2', 'local_name' => 'سيح شعيب 2', 'district_id' => 5, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saih Shuaib 3', 'local_name' => 'سيح شعيب 3', 'district_id' => 5, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saih Shuaib 4', 'local_name' => 'سيح شعيب 4', 'district_id' => 5, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jebel Ali First', 'local_name' => 'جبل علي الأولى', 'district_id' => 5, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jebel Ali Second', 'local_name' => 'جبل علي الثانية', 'district_id' => 5, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jebel Ali Third', 'local_name' => 'جبل علي الثالثة', 'district_id' => 5, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mena Jebel Ali', 'local_name' => 'ميناء جبل علي', 'district_id' => 5, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dubai Investment Park Second', 'local_name' => 'مجمع دبي للاستثمار الثاني', 'district_id' => 5, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dubai Investment Park First', 'local_name' => 'مجمع دبي للاستثمار الأول', 'district_id' => 5, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jebel Ali Industrial First', 'local_name' => 'جبل علي الصناعية الأولى', 'district_id' => 5, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bu Kadra', 'local_name' => 'بو كدرة', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ras Al Khor Industrial First', 'local_name' => 'رأس الخور الصناعية الأولى', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ras Al Khor Industrial Second', 'local_name' => 'رأس الخور الصناعية الثانية', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ras Al Khor Industrial Third', 'local_name' => 'رأس الخور الصناعية الثالثة', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nad Al Sheba Second', 'local_name' => 'ند الشبا الثانية', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nad Al Sheba Third', 'local_name' => 'ند الشبا الثالثة', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nad Al Sheba Fourth', 'local_name' => 'ند الشبا الرابعة', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nad Al Sheba First', 'local_name' => 'ند الشبا الأولى', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Warsan First', 'local_name' => 'ورسان الاولى', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Warsan Second', 'local_name' => 'ورسان الثانية', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Warsan Fourth', 'local_name' => 'ورسان الرابعة', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nad Hessa', 'local_name' => 'ند حصة', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hadaeq Sheikh Mohammed Bin Rashid', 'local_name' => 'حدائق الشيخ محمد بن راشد', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wadi Al Safa 2', 'local_name' => 'وادي الصفا 2', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wadi Al Safa 3', 'local_name' => 'وادي الصفا 3', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wadi Al Safa 4', 'local_name' => 'وادي الصفا 4', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wadi Al Safa 5', 'local_name' => 'وادي الصفا 5', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wadi Al Safa 6', 'local_name' => 'وادي الصفا 6', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wadi Al Safa 7', 'local_name' => 'وادي الصفا 7', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Barsha South First', 'local_name' => 'البرشاء جنوب الاولى', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Barsha South Second', 'local_name' => 'البرشاء جنوب الثانية', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Barsha South Third', 'local_name' => 'البرشاء جنوب الثالثة', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hebiah First', 'local_name' => 'الحبيه الاول', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hebiah Second', 'local_name' => 'الحبيه الثانية', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hebiah Third', 'local_name' => 'الحبيه الثالثة', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hebiah Sixth', 'local_name' => 'الحبيه السادسة', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Barsha South Fourth', 'local_name' => 'البرشاء جنوب الرابعة', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hebiah Fourth', 'local_name' => 'الحبيه الرابعة', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hebiah Fifth', 'local_name' => 'الحبيه الخامسة', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Barsha South Fifth', 'local_name' => 'البرشاء جنوب الخامسة', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Me`aisem First', 'local_name' => 'معيصم الأول', 'district_id' => 6, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Me`aisem Second', 'local_name' => 'معيصم الثانية', 'district_id' => 6, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Awir First', 'local_name' => 'العوير الأولى', 'district_id' => 7, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Awir Second', 'local_name' => 'العوير الثانية', 'district_id' => 7, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Enkhali', 'local_name' => 'نخلي', 'district_id' => 7, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Wohoosh', 'local_name' => 'الوحوش', 'district_id' => 7, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lehbab First', 'local_name' => 'لهباب الأولى', 'district_id' => 7, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Meryal', 'local_name' => 'المريال', 'district_id' => 7, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nazwah', 'local_name' => 'نزوه', 'district_id' => 7, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Warsan 3', 'local_name' => 'ورسان الثالثة', 'district_id' => 8, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Rowaiyah First', 'local_name' => 'الرويه الأولى', 'district_id' => 8, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Rowaiyah Second', 'local_name' => 'الرويه الثانية', 'district_id' => 8, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Rowaiyah Third', 'local_name' => 'الرويه الثالثة', 'district_id' => 8, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mereiyeel', 'local_name' => 'مرييل', 'district_id' => 8, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Umm Al Daman', 'local_name' => 'أم الدمن', 'district_id' => 8, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Le Hemaira', 'local_name' => 'الحميرا', 'district_id' => 8, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lehbab Second', 'local_name' => 'لهباب الثانية', 'district_id' => 8, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Umm Al Mo`meneen', 'local_name' => 'أم المؤمنين', 'district_id' => 8, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Margham', 'local_name' => 'مرغم', 'district_id' => 8, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Maha', 'local_name' => 'المها', 'district_id' => 8, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Umm Eselay', 'local_name' => 'أم السلي', 'district_id' => 8, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Remah', 'local_name' => 'رماح', 'district_id' => 8, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Margab', 'local_name' => 'مرقب', 'district_id' => 8, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Yaraah', 'local_name' => 'يراح', 'district_id' => 8, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hatta', 'local_name' => 'حتا', 'district_id' => 8, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Madinat Hind 1', 'local_name' => 'مدينة هند 1', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Madinat Hind 2', 'local_name' => 'مدينة هند 2', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Madinat Hind 3', 'local_name' => 'مدينة هند 3', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Madinat Hind 4', 'local_name' => 'مدينة هند 4', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Yufrah 1', 'local_name' => 'اليفره 1', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Marmoom', 'local_name' => 'المرموم', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Yufrah 2', 'local_name' => 'اليفره 2', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Yalayis 1', 'local_name' => 'الياليس 1', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Yalayis 2', 'local_name' => 'الياليس 2', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Yalayis 3', 'local_name' => 'الياليس 3', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Yalayis 4', 'local_name' => 'الياليس 4', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Yalayis 5', 'local_name' => 'الياليس 5', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Lesaily', 'local_name' => 'الليسيلي', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Grayteesah', 'local_name' => 'قريطيسه', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Fagaa', 'local_name' => 'الفقع', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saih Al Salam', 'local_name' => 'سيح السلم', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hathmah', 'local_name' => 'الحثمة', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Madinat Latifa', 'local_name' => 'مدينة لطيفة', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ghadeer Barashy', 'local_name' => 'غدير براشي', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saih Al Dahal', 'local_name' => 'سيح الدحل', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al O`shoosh', 'local_name' => 'العشوش', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saih Shua`alah', 'local_name' => 'سيح شعيله', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mugatrah', 'local_name' => 'مقطره', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Layan 1', 'local_name' => 'الليان 1', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Layan 2', 'local_name' => 'الليان 2', 'district_id' => 9, 'latitude' => 25.2711, 'longitude' => 55.3026, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hefair', 'local_name' => 'حفير', 'district_id' => 9, 'latitude' => 25.2743, 'longitude' => 55.3097, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            // Records from image
            ['name' => 'Dibba Al-Hisn', 'local_name' => 'دبا الحصن', 'district_id' => 21, 'latitude' => 25.6199, 'longitude' => 56.2725, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Nuaimia', 'local_name' => 'النعيمية', 'district_id' => 22, 'latitude' => 25.3986, 'longitude' => 55.479, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Rawda', 'local_name' => 'الروضة', 'district_id' => 22, 'latitude' => 25.3995, 'longitude' => 55.5172, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Jerf', 'local_name' => 'الجرف', 'district_id' => 22, 'latitude' => 25.411, 'longitude' => 55.5296, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hamidiya', 'local_name' => 'الحميدية', 'district_id' => 22, 'latitude' => 25.3734, 'longitude' => 55.5064, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Rumailah', 'local_name' => 'الرميلة', 'district_id' => 22, 'latitude' => 25.4014, 'longitude' => 55.4414, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Nakhil', 'local_name' => 'النخيل', 'district_id' => 22, 'latitude' => 25.3928, 'longitude' => 55.4335, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Zorah', 'local_name' => 'الزوراء', 'district_id' => 22, 'latitude' => 25.4234, 'longitude' => 55.4975, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Heliow', 'local_name' => 'الحليو', 'district_id' => 22, 'latitude' => 25.4334, 'longitude' => 55.5723, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ajman Industrial areas', 'local_name' => 'مناطق عجمان الصناعية', 'district_id' => 22, 'latitude' => 25.3849, 'longitude' => 55.5037, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Manama', 'local_name' => 'المنامة', 'district_id' => 23, 'latitude' => 25.3869, 'longitude' => 56.0371, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Masfout', 'local_name' => 'مصفوت', 'district_id' => 24, 'latitude' => 24.8177, 'longitude' => 56.0561, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Jazeera', 'local_name' => 'الجزيرة', 'district_id' => 25, 'latitude' => 25.675, 'longitude' => 55.766, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Arouq', 'local_name' => 'العروق', 'district_id' => 25, 'latitude' => 25.715, 'longitude' => 55.934, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Dhait North', 'local_name' => 'الضيت الشمالي', 'district_id' => 25, 'latitude' => 25.7877, 'longitude' => 55.9772, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Dhait South', 'local_name' => 'الضيت الجنوبي', 'district_id' => 25, 'latitude' => 25.7693, 'longitude' => 55.9791, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Ghubb', 'local_name' => 'الغب', 'district_id' => 25, 'latitude' => 25.761, 'longitude' => 55.9602, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hamraniyah', 'local_name' => 'الحمرانية', 'district_id' => 25, 'latitude' => 25.639, 'longitude' => 55.852, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hudaibah', 'local_name' => 'الحضيبة', 'district_id' => 25, 'latitude' => 25.684, 'longitude' => 55.785, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Juwais', 'local_name' => 'الجويس', 'district_id' => 25, 'latitude' => 25.692, 'longitude' => 55.803, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Kharran', 'local_name' => 'الخران', 'district_id' => 25, 'latitude' => 25.724, 'longitude' => 55.819, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Maarid', 'local_name' => 'المعيريض', 'district_id' => 25, 'latitude' => 25.796, 'longitude' => 55.957, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Mamourah', 'local_name' => 'المعمورة', 'district_id' => 25, 'latitude' => 25.777, 'longitude' => 55.963, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Nadiyah', 'local_name' => 'النادية', 'district_id' => 25, 'latitude' => 25.667, 'longitude' => 55.732, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Nakheel', 'local_name' => 'النخيل', 'district_id' => 25, 'latitude' => 25.789, 'longitude' => 55.95, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Qurm', 'local_name' => 'القرم', 'district_id' => 25, 'latitude' => 25.614, 'longitude' => 55.738, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Qusaidat', 'local_name' => 'القصيدات', 'district_id' => 25, 'latitude' => 25.729, 'longitude' => 55.952, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Rams', 'local_name' => 'الرمس', 'district_id' => 25, 'latitude' => 25.9068, 'longitude' => 56.0467, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Saween', 'local_name' => 'السوين', 'district_id' => 25, 'latitude' => 25.81, 'longitude' => 55.893, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Shansha', 'local_name' => 'الشنشة', 'district_id' => 25, 'latitude' => 25.734, 'longitude' => 55.905, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Tharfah', 'local_name' => 'الطرفة', 'district_id' => 25, 'latitude' => 25.751, 'longitude' => 55.881, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Uraibi', 'local_name' => 'العريبي', 'district_id' => 25, 'latitude' => 25.79, 'longitude' => 55.941, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Khuzam', 'local_name' => 'خزام', 'district_id' => 25, 'latitude' => 25.7932, 'longitude' => 55.9509, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dafan Al Khor', 'local_name' => 'دفن الخور', 'district_id' => 25, 'latitude' => 25.805, 'longitude' => 55.976, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dahan', 'local_name' => 'دهان', 'district_id' => 25, 'latitude' => 25.658, 'longitude' => 55.828, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Digdaga', 'local_name' => 'دقداقة', 'district_id' => 25, 'latitude' => 25.6019, 'longitude' => 55.8913, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ghalilah', 'local_name' => 'غليلة', 'district_id' => 25, 'latitude' => 25.802, 'longitude' => 55.967, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Madinat Khalifa bin Zayed', 'local_name' => 'مدينة خليفة بن زايد', 'district_id' => 25, 'latitude' => 25.695, 'longitude' => 55.783, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Old Town', 'local_name' => 'البلدة القديمة', 'district_id' => 25, 'latitude' => 25.794, 'longitude' => 55.939, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sidroh', 'local_name' => 'سدروه', 'district_id' => 25, 'latitude' => 25.78, 'longitude' => 55.933, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Suhailah', 'local_name' => 'سهيلة', 'district_id' => 25, 'latitude' => 25.739, 'longitude' => 55.923, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            // Abu Dhabi District Records
            ['name' => 'Abu Dhabi City', 'local_name' => 'أبوظبي', 'district_id' => 10, 'latitude' => 24.4539, 'longitude' => 54.3773, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Abu Al Abyad', 'local_name' => 'أبو الأبيض', 'district_id' => 10, 'latitude' => 24.125, 'longitude' => 53.8333, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al-Aryam Island', 'local_name' => 'جزيرة الأريام', 'district_id' => 10, 'latitude' => 24.418, 'longitude' => 53.893, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al-Bahiyah', 'local_name' => 'الباهية', 'district_id' => 10, 'latitude' => 24.571, 'longitude' => 54.7188, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al-Shahamah', 'local_name' => 'الشهامة', 'district_id' => 10, 'latitude' => 24.5327, 'longitude' => 54.6794, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al-Wathbah', 'local_name' => 'الوثبة', 'district_id' => 10, 'latitude' => 24.2612, 'longitude' => 54.6535, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bani Yas City', 'local_name' => 'بني ياس', 'district_id' => 10, 'latitude' => 24.3485, 'longitude' => 54.6218, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ghantoot', 'local_name' => 'غنتوت', 'district_id' => 10, 'latitude' => 24.8923, 'longitude' => 54.9713, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Halat Al Bahrani', 'local_name' => 'حالة البحراني', 'district_id' => 10, 'latitude' => 24.202, 'longitude' => 54.023, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jubail Island', 'local_name' => 'جزيرة الجبيل', 'district_id' => 10, 'latitude' => 24.5205, 'longitude' => 54.4671, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Khalifa Port', 'local_name' => 'ميناء خليفة', 'district_id' => 10, 'latitude' => 24.8074, 'longitude' => 54.9743, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Masdar City', 'local_name' => 'مدينة مصدر', 'district_id' => 10, 'latitude' => 24.4269, 'longitude' => 54.6175, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mina Zayed', 'local_name' => 'ميناء زايد', 'district_id' => 10, 'latitude' => 24.5258, 'longitude' => 54.385, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mussafah', 'local_name' => 'مصفح', 'district_id' => 10, 'latitude' => 24.3865, 'longitude' => 54.5183, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saadiyat Island', 'local_name' => 'جزيرة السعديات', 'district_id' => 10, 'latitude' => 24.5432, 'longitude' => 54.432, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Yas Island', 'local_name' => 'جزيرة ياس', 'district_id' => 10, 'latitude' => 24.4958, 'longitude' => 54.604, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Tawelah', 'local_name' => 'الطويلة', 'district_id' => 10, 'latitude' => 24.39, 'longitude' => 54.71, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Shaleelah', 'local_name' => 'الشليلة', 'district_id' => 10, 'latitude' => 24.33, 'longitude' => 54.54, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Shamkhah', 'local_name' => 'الشامخة', 'district_id' => 10, 'latitude' => 24.3956, 'longitude' => 54.6417, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Muazz', 'local_name' => 'المعزز', 'district_id' => 10, 'latitude' => 24.378, 'longitude' => 54.612, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Madinat Zayed', 'local_name' => 'مدينة زايد', 'district_id' => 10, 'latitude' => 23.6542, 'longitude' => 53.7058, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            // Western Region (Al Gharbia) Records
            ['name' => 'Ghayathi', 'local_name' => 'غياثي', 'district_id' => 11, 'latitude' => 23.885, 'longitude' => 52.7325, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ghuwaifat', 'local_name' => 'الغويفات', 'district_id' => 11, 'latitude' => 23.973, 'longitude' => 51.763, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Habshan', 'local_name' => 'حبشان', 'district_id' => 11, 'latitude' => 23.9213, 'longitude' => 53.6492, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Liwa Oasis', 'local_name' => 'واحة ليوا', 'district_id' => 11, 'latitude' => 23.1294, 'longitude' => 53.7821, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marawah Island', 'local_name' => 'جزيرة مروح', 'district_id' => 11, 'latitude' => 24.205, 'longitude' => 53.4117, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ruwais', 'local_name' => 'الرويس', 'district_id' => 11, 'latitude' => 24.1108, 'longitude' => 52.7306, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sila', 'local_name' => 'السلع', 'district_id' => 11, 'latitude' => 24.0666, 'longitude' => 51.838, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sir Bani Yas', 'local_name' => 'جزيرة صير بني ياس', 'district_id' => 11, 'latitude' => 24.322, 'longitude' => 52.6156, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tarif', 'local_name' => 'طريف', 'district_id' => 11, 'latitude' => 23.6419, 'longitude' => 53.6893, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            // Al Ain Region Records
            ['name' => 'Al Ain City', 'local_name' => 'العين', 'district_id' => 12, 'latitude' => 24.2075, 'longitude' => 55.7447, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al-Faqa', 'local_name' => 'الفقع', 'district_id' => 12, 'latitude' => 24.8667, 'longitude' => 55.6027, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hayer', 'local_name' => 'الهير', 'district_id' => 12, 'latitude' => 24.4976, 'longitude' => 55.7053, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al-Qu', 'local_name' => 'القوع', 'district_id' => 12, 'latitude' => 23.9771, 'longitude' => 55.7041, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Shwaib', 'local_name' => 'الشعيب', 'district_id' => 12, 'latitude' => 24.7083, 'longitude' => 55.8481, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Wagan', 'local_name' => 'الوقن', 'district_id' => 12, 'latitude' => 23.5598, 'longitude' => 55.5324, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al-Yahar', 'local_name' => 'اليحر', 'district_id' => 12, 'latitude' => 24.15, 'longitude' => 55.65, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mezyad', 'local_name' => 'مزيد', 'district_id' => 12, 'latitude' => 24.0869, 'longitude' => 55.7497, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nahil', 'local_name' => 'ناهل', 'district_id' => 12, 'latitude' => 24.2877, 'longitude' => 55.3789, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Ajban', 'local_name' => 'العجبان', 'district_id' => 12, 'latitude' => 24.5051, 'longitude' => 55.0414, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Remah', 'local_name' => 'رماح', 'district_id' => 12, 'latitude' => 24.2022, 'longitude' => 55.5852, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Seih', 'local_name' => 'سيح', 'district_id' => 12, 'latitude' => 24.4942, 'longitude' => 55.4878, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sweihan', 'local_name' => 'سويحان', 'district_id' => 12, 'latitude' => 24.4637, 'longitude' => 55.3514, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            // District 13 Records
            ['name' => 'Al Nahda qua', 'local_name' => 'حي النهدة', 'district_id' => 13, 'latitude' => 25.2975, 'longitude' => 55.3753, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Majaz', 'local_name' => 'حي المجاز', 'district_id' => 13, 'latitude' => 25.2866, 'longitude' => 55.3854, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Gharb', 'local_name' => 'الغرب', 'district_id' => 13, 'latitude' => 25.3617, 'longitude' => 55.3925, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Qasimia', 'local_name' => 'القاسمية', 'district_id' => 13, 'latitude' => 25.3538, 'longitude' => 55.3894, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Sharq', 'local_name' => 'الشرق', 'district_id' => 13, 'latitude' => 25.3612, 'longitude' => 55.3971, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Seifa', 'local_name' => 'السيفة', 'district_id' => 13, 'latitude' => 25.2925, 'longitude' => 55.371, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Jazeera sub', 'local_name' => 'ضاحية الجزيرة', 'district_id' => 13, 'latitude' => 25.3313, 'longitude' => 55.3712, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tujarrett Mix', 'local_name' => 'تجارة مويلح', 'district_id' => 13, 'latitude' => 25.313, 'longitude' => 55.4492, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Riqqat sub', 'local_name' => 'ضاحية الرقة', 'district_id' => 13, 'latitude' => 25.3608, 'longitude' => 55.4233, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Halwan subur', 'local_name' => 'ضاحية حلوان', 'district_id' => 13, 'latitude' => 25.3406, 'longitude' => 55.4289, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hiyar Subu', 'local_name' => 'ضاحية الحيل', 'district_id' => 13, 'latitude' => 25.39, 'longitude' => 55.4141, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mughaidir su', 'local_name' => 'ضاحية مغيدر', 'district_id' => 13, 'latitude' => 25.3233, 'longitude' => 55.4397, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wasut subur', 'local_name' => 'ضاحية وسط', 'district_id' => 13, 'latitude' => 25.3655, 'longitude' => 55.448, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Muwaih subu', 'local_name' => 'ضاحية مويلح', 'district_id' => 13, 'latitude' => 25.2772, 'longitude' => 55.522, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Sajaa', 'local_name' => 'السجعة', 'district_id' => 13, 'latitude' => 25.3655, 'longitude' => 55.6609, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Ruqa Al Ha', 'local_name' => 'الرقة الحمرا', 'district_id' => 13, 'latitude' => 25.1885, 'longitude' => 55.5139, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'University Ci', 'local_name' => 'المدينة الجامعية', 'district_id' => 13, 'latitude' => 25.2899, 'longitude' => 55.484, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Rahmaniyah s', 'local_name' => 'ضاحية الرحمانية', 'district_id' => 13, 'latitude' => 25.352, 'longitude' => 55.5515, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bastakyia AZ', 'local_name' => 'البستكية', 'district_id' => 13, 'latitude' => 25.3875, 'longitude' => 55.6102, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Budaiya su', 'local_name' => 'ضاحية البديع', 'district_id' => 13, 'latitude' => 25.2793, 'longitude' => 55.5234, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Khalid Sea Po', 'local_name' => 'ميناء خالد', 'district_id' => 13, 'latitude' => 25.364, 'longitude' => 55.3775, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Siyahi subu', 'local_name' => 'ضاحية السياحي', 'district_id' => 13, 'latitude' => 25.21568, 'longitude' => 55.62583, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Zubair', 'local_name' => 'الزبير', 'district_id' => 13, 'latitude' => 25.3942, 'longitude' => 55.6401, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kaya Masaar', 'local_name' => 'كايا مسار', 'district_id' => 13, 'latitude' => 25.2676, 'longitude' => 55.6412, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Jat', 'local_name' => 'الجعل', 'district_id' => 13, 'latitude' => 25.3545, 'longitude' => 55.5576, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Shrouf', 'local_name' => 'الشروف', 'district_id' => 13, 'latitude' => 25.3891, 'longitude' => 55.7265, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Suburb of Jwe', 'local_name' => 'ضاحية جويزع', 'district_id' => 13, 'latitude' => 25.2729, 'longitude' => 55.6079, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mehafiz', 'local_name' => 'محافظ', 'district_id' => 13, 'latitude' => 25.4047, 'longitude' => 55.6424, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Tay subur', 'local_name' => 'ضاحية الطي', 'district_id' => 13, 'latitude' => 25.21376, 'longitude' => 55.6308, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Sidairah', 'local_name' => 'السديرة', 'district_id' => 13, 'latitude' => 25.3382, 'longitude' => 55.6796, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hamriyah', 'local_name' => 'الحمرية', 'district_id' => 14, 'latitude' => 25.4762, 'longitude' => 55.5058, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Bataeh', 'local_name' => 'البطائح', 'district_id' => 15, 'latitude' => 25.2139, 'longitude' => 55.6189, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Madam', 'local_name' => 'المدام', 'district_id' => 16, 'latitude' => 24.9812, 'longitude' => 55.7805, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mleiha', 'local_name' => 'مليحة', 'district_id' => 17, 'latitude' => 25.1406, 'longitude' => 55.8439, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dhaid', 'local_name' => 'الذيد', 'district_id' => 18, 'latitude' => 25.2885, 'longitude' => 55.8818, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kalba', 'local_name' => 'كلباء', 'district_id' => 19, 'latitude' => 25.0657, 'longitude' => 56.3572, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Khor Fakkan', 'local_name' => 'خور فكان', 'district_id' => 20, 'latitude' => 25.3454, 'longitude' => 56.3629, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            // Additional Records
            ['name' => 'Al Jazirah Al Hamra', 'local_name' => 'الجزيرة الحمراء', 'district_id' => 26, 'latitude' => 25.6719, 'longitude' => 55.7586, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Rams', 'local_name' => 'الرمس', 'district_id' => 27, 'latitude' => 25.9088, 'longitude' => 56.0467, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Khor Khwair', 'local_name' => 'خور خوير', 'district_id' => 28, 'latitude' => 25.9835, 'longitude' => 56.0554, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Diqdaqah', 'local_name' => 'دقداقة', 'district_id' => 29, 'latitude' => 25.6019, 'longitude' => 55.8913, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Khatt', 'local_name' => 'خت', 'district_id' => 30, 'latitude' => 25.7133, 'longitude' => 56.0562, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Masafi', 'local_name' => 'مسافي', 'district_id' => 31, 'latitude' => 25.3147, 'longitude' => 56.1649, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Huwaylat', 'local_name' => 'حويلات', 'district_id' => 32, 'latitude' => 25.8927, 'longitude' => 56.0359, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sha\'am', 'local_name' => 'شعم', 'district_id' => 33, 'latitude' => 26.049, 'longitude' => 56.058, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Badiyah', 'local_name' => 'البدية', 'district_id' => 34, 'latitude' => 25.4397, 'longitude' => 56.3599, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Bithnah', 'local_name' => 'البثنة', 'district_id' => 34, 'latitude' => 25.181, 'longitude' => 56.2315, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Qurayah', 'local_name' => 'القرية', 'district_id' => 34, 'latitude' => 25.2325, 'longitude' => 56.3617, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dhadna', 'local_name' => 'دهدنا', 'district_id' => 34, 'latitude' => 25.52, 'longitude' => 56.362, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dahir', 'local_name' => 'ظاهر', 'district_id' => 34, 'latitude' => 25.515, 'longitude' => 56.3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dibba Al-Fujairah', 'local_name' => 'دبا الفجيرة', 'district_id' => 34, 'latitude' => 25.5911, 'longitude' => 56.2618, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Fujairah', 'local_name' => 'الفجيرة', 'district_id' => 34, 'latitude' => 25.4111, 'longitude' => 56.2482, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Hayl', 'local_name' => 'الحيل', 'district_id' => 34, 'latitude' => 25.1297, 'longitude' => 56.2738, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Rugaylat', 'local_name' => 'الرغيلات', 'district_id' => 34, 'latitude' => 25.3773, 'longitude' => 56.3473, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Habhab', 'local_name' => 'حبحب', 'district_id' => 34, 'latitude' => 25.6, 'longitude' => 56.1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hafarah', 'local_name' => 'حفيرة', 'district_id' => 34, 'latitude' => 25.55, 'longitude' => 56.1333, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Harrah', 'local_name' => 'حرة', 'district_id' => 34, 'latitude' => 25.18, 'longitude' => 56.28, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Masafi', 'local_name' => 'مسافي', 'district_id' => 34, 'latitude' => 25.3147, 'longitude' => 56.1649, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Maydaq', 'local_name' => 'ميدق', 'district_id' => 34, 'latitude' => 25.31, 'longitude' => 56.155, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mirbah', 'local_name' => 'مربح', 'district_id' => 34, 'latitude' => 25.2762, 'longitude' => 56.3627, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mukhtaraqah', 'local_name' => 'المخترقة', 'district_id' => 34, 'latitude' => 25.45, 'longitude' => 56.33, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Murbad', 'local_name' => 'المربد', 'district_id' => 34, 'latitude' => 25.26, 'longitude' => 56.32, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mu\'taridah', 'local_name' => 'المعترضة', 'district_id' => 34, 'latitude' => 25.284, 'longitude' => 56.25, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Qidfa', 'local_name' => 'قدفع', 'district_id' => 34, 'latitude' => 25.273, 'longitude' => 56.3419, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Salamkam', 'local_name' => 'سكمكم', 'district_id' => 34, 'latitude' => 25.3583, 'longitude' => 56.303, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tayyibah', 'local_name' => 'طيبة', 'district_id' => 34, 'latitude' => 25.6, 'longitude' => 56.2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Umm Al Quwain', 'local_name' => 'أم القيوين', 'district_id' => 35, 'latitude' => 25.5889, 'longitude' => 55.5763, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Falaj Al Mualla', 'local_name' => 'فلج المعلا', 'district_id' => 36, 'latitude' => 25.3214, 'longitude' => 55.8812, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Siniyah Island', 'local_name' => 'جزيرة السنية', 'district_id' => 37, 'latitude' => 25.593, 'longitude' => 55.588, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Rafaah', 'local_name' => 'الرفاعة', 'district_id' => 38, 'latitude' => 25.502, 'longitude' => 55.644, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Salamah', 'local_name' => 'السلامة', 'district_id' => 39, 'latitude' => 25.518, 'longitude' => 55.6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Darer', 'local_name' => 'الدرر', 'district_id' => 40, 'latitude' => 25.512, 'longitude' => 55.63, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            // Additional Records
            ['name' => 'Al Suehat', 'local_name' => 'السويحات', 'district_id' => 41, 'latitude' => 25.52, 'longitude' => 55.61, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tell Abraq', 'local_name' => 'تل الأبرق', 'district_id' => 42, 'latitude' => 25.494, 'longitude' => 55.654, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ramla', 'local_name' => 'رملة', 'district_id' => 43, 'latitude' => 25.5, 'longitude' => 55.64, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Labsah', 'local_name' => 'اللبسة', 'district_id' => 44, 'latitude' => 25.509, 'longitude' => 55.62, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Rashidiya', 'local_name' => 'الرشيدية', 'district_id' => 45, 'latitude' => 25.525, 'longitude' => 55.615, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Biyatah', 'local_name' => 'بياتة', 'district_id' => 46, 'latitude' => 25.53, 'longitude' => 55.61, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Atheab', 'local_name' => 'الذيب', 'district_id' => 47, 'latitude' => 25.536, 'longitude' => 55.603, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Khor Al Beidah', 'local_name' => 'خور البيضا', 'district_id' => 48, 'latitude' => 25.548, 'longitude' => 55.599, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Al Serra', 'local_name' => 'السرة', 'district_id' => 49, 'latitude' => 25.543, 'longitude' => 55.605, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mohadub', 'local_name' => 'مهذب', 'district_id' => 50, 'latitude' => 25.54, 'longitude' => 55.62, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kabir', 'local_name' => 'كابر', 'district_id' => 51, 'latitude' => 25.545, 'longitude' => 55.626, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jazirat Al Aklab', 'local_name' => 'جزيرة الأكلاب', 'district_id' => 52, 'latitude' => 25.552, 'longitude' => 55.595, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jazirat al Ghallah', 'local_name' => 'جزيرة الغلة', 'district_id' => 53, 'latitude' => 25.547, 'longitude' => 55.597, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now]
        ];

        foreach ($neighbours as $neighbour) {
            Neighbour::updateOrCreate(
                [
                    'name' => $neighbour['name'],
                    'district_id' => $neighbour['district_id']
                ],
                $neighbour
            );
        }
    }
}
