<?php

namespace Database\Seeders;

use App\Models\OfferCategory;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class OfferCategorySeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now()->toDateTimeString();

        $categories = [
            ['id' => 1, 'name' => 'Shopping & Retail', 'icon' => 'fas fa-fas fa-shopping-bag', 'color' => '#F97316', 'order' => 1, 'active' => 1, 'parent_id' => null, 'description' => 'Shopping & Retail related offers and discounts.', 'slug' => 'shopping-and-retail', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 2, 'name' => 'Supermarkets & Hypermarkets', 'icon' => 'fas fa-fas fa-shopping-bag', 'color' => '#F97316', 'order' => 2, 'active' => 1, 'parent_id' => 1, 'description' => 'Supermarkets & Hypermarkets offers and deals in the UAE.', 'slug' => 'supermarkets-and-hypermarkets', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 3, 'name' => 'Fashion & Clothing', 'icon' => 'fas fa-shopping-bag', 'color' => '#F97316', 'order' => 3, 'active' => 1, 'parent_id' => 1, 'description' => 'Fashion & Clothing offers and deals in the UAE.', 'slug' => 'fashion-and-clothing', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 4, 'name' => 'Beauty & Personal Care', 'icon' => 'fas fa-shopping-bag', 'color' => '#F97316', 'order' => 4, 'active' => 1, 'parent_id' => 1, 'description' => 'Beauty & Personal Care offers and deals in the UAE.', 'slug' => 'beauty-and-personal-care', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 5, 'name' => 'Home Appliances', 'icon' => 'fas fa-shopping-bag', 'color' => '#F97316', 'order' => 5, 'active' => 1, 'parent_id' => 1, 'description' => 'Home Appliances offers and deals in the UAE.', 'slug' => 'home-appliances', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 6, 'name' => 'Electronics & Mobile', 'icon' => 'fas fa-shopping-bag', 'color' => '#F97316', 'order' => 6, 'active' => 1, 'parent_id' => 1, 'description' => 'Electronics & Mobile offers and deals in the UAE.', 'slug' => 'electronics-and-mobile', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 7, 'name' => 'Kids & Toys', 'icon' => 'fas fa-shopping-bag', 'color' => '#F97316', 'order' => 7, 'active' => 1, 'parent_id' => 1, 'description' => 'Kids & Toys offers and deals in the UAE.', 'slug' => 'kids-and-toys', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 8, 'name' => 'Books & Stationery', 'icon' => 'fas fa-shopping-bag', 'color' => '#F97316', 'order' => 8, 'active' => 1, 'parent_id' => 1, 'description' => 'Books & Stationery offers and deals in the UAE.', 'slug' => 'books-and-stationery', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 9, 'name' => 'Food & Beverages', 'icon' => 'fas fa-utensils', 'color' => '#10B981', 'order' => 9, 'active' => 1, 'parent_id' => null, 'description' => 'Food & Beverages related offers and discounts.', 'slug' => 'food-and-beverages', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 10, 'name' => 'Restaurants', 'icon' => 'fas fa-utensils', 'color' => '#10B981', 'order' => 10, 'active' => 1, 'parent_id' => 9, 'description' => 'Restaurants offers and deals in the UAE.', 'slug' => 'restaurants', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 11, 'name' => 'Fast Food', 'icon' => 'fas fa-utensils', 'color' => '#10B981', 'order' => 11, 'active' => 1, 'parent_id' => 9, 'description' => 'Fast Food offers and deals in the UAE.', 'slug' => 'fast-food', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 12, 'name' => 'Cafés & Coffee Shops', 'icon' => 'fas fa-utensils', 'color' => '#10B981', 'order' => 12, 'active' => 1, 'parent_id' => 9, 'description' => 'Cafés & Coffee Shops offers and deals in the UAE.', 'slug' => 'cafés-and-coffee-shops', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 13, 'name' => 'Online Food Delivery', 'icon' => 'fas fa-utensils', 'color' => '#10B981', 'order' => 13, 'active' => 1, 'parent_id' => 9, 'description' => 'Online Food Delivery offers and deals in the UAE.', 'slug' => 'online-food-delivery', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 14, 'name' => 'Organic & Specialty Food Stores', 'icon' => 'fas fa-utensils', 'color' => '#10B981', 'order' => 14, 'active' => 1, 'parent_id' => 9, 'description' => 'Organic & Specialty Food Stores offers and deals in the UAE.', 'slug' => 'organic-and-specialty-food-stores', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 15, 'name' => 'Beauty & Health Services', 'icon' => 'fas fa-spa', 'color' => '#8B5CF6', 'order' => 15, 'active' => 1, 'parent_id' => null, 'description' => 'Beauty & Health Services related offers and discounts.', 'slug' => 'beauty-and-health-services', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 16, 'name' => 'Beauty Salons & Barbershops', 'icon' => 'fas fa-spa', 'color' => '#8B5CF6', 'order' => 16, 'active' => 1, 'parent_id' => 15, 'description' => 'Beauty Salons & Barbershops offers and deals in the UAE.', 'slug' => 'beauty-salons-and-barbershops', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 17, 'name' => 'Spas & Massage Centers', 'icon' => 'fas fa-spa', 'color' => '#8B5CF6', 'order' => 17, 'active' => 1, 'parent_id' => 15, 'description' => 'Spas & Massage Centers offers and deals in the UAE.', 'slug' => 'spas-and-massage-centers', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 18, 'name' => 'Skin & Hair Clinics', 'icon' => 'fas fa-spa', 'color' => '#8B5CF6', 'order' => 18, 'active' => 1, 'parent_id' => 15, 'description' => 'Skin & Hair Clinics offers and deals in the UAE.', 'slug' => 'skin-and-hair-clinics', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 19, 'name' => 'Fitness & Gyms', 'icon' => 'fas fa-spa', 'color' => '#8B5CF6', 'order' => 19, 'active' => 1, 'parent_id' => 15, 'description' => 'Fitness & Gyms offers and deals in the UAE.', 'slug' => 'fitness-and-gyms', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 20, 'name' => 'Medical & Dental Services', 'icon' => 'fas fa-spa', 'color' => '#8B5CF6', 'order' => 20, 'active' => 1, 'parent_id' => 15, 'description' => 'Medical & Dental Services offers and deals in the UAE.', 'slug' => 'medical-and-dental-services', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 21, 'name' => 'Leisure & Travel', 'icon' => 'fas fa-umbrella-beach', 'color' => '#3B82F6', 'order' => 21, 'active' => 1, 'parent_id' => null, 'description' => 'Leisure & Travel related offers and discounts.', 'slug' => 'leisure-and-travel', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 22, 'name' => 'Tour Packages & Travel Offers', 'icon' => 'fas fa-umbrella-beach', 'color' => '#3B82F6', 'order' => 22, 'active' => 1, 'parent_id' => 21, 'description' => 'Tour Packages & Travel Offers offers and deals in the UAE.', 'slug' => 'tour-packages-and-travel-offers', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 23, 'name' => 'Concerts & Event Tickets', 'icon' => 'fas fa-umbrella-beach', 'color' => '#3B82F6', 'order' => 23, 'active' => 1, 'parent_id' => 21, 'description' => 'Concerts & Event Tickets offers and deals in the UAE.', 'slug' => 'concerts-and-event-tickets', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 24, 'name' => 'Family Parks & Attractions', 'icon' => 'fas fa-umbrella-beach', 'color' => '#3B82F6', 'order' => 24, 'active' => 1, 'parent_id' => 21, 'description' => 'Family Parks & Attractions offers and deals in the UAE.', 'slug' => 'family-parks-and-attractions', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 25, 'name' => 'Hotels, Villas & Accommodations', 'icon' => 'fas fa-umbrella-beach', 'color' => '#3B82F6', 'order' => 25, 'active' => 1, 'parent_id' => 21, 'description' => 'Hotels, Villas & Accommodations offers and deals in the UAE.', 'slug' => 'hotels,-villas-and-accommodations', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 26, 'name' => 'Car Rentals', 'icon' => 'fas fa-umbrella-beach', 'color' => '#3B82F6', 'order' => 26, 'active' => 1, 'parent_id' => 21, 'description' => 'Car Rentals offers and deals in the UAE.', 'slug' => 'car-rentals', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 27, 'name' => 'Local Services & B2B', 'icon' => 'fas fa-tools', 'color' => '#F59E0B', 'order' => 27, 'active' => 1, 'parent_id' => null, 'description' => 'Local Services & B2B related offers and discounts.', 'slug' => 'local-services-and-b2b', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 28, 'name' => 'Car Wash & Auto Services', 'icon' => 'fas fa-tools', 'color' => '#F59E0B', 'order' => 28, 'active' => 1, 'parent_id' => 27, 'description' => 'Car Wash & Auto Services offers and deals in the UAE.', 'slug' => 'car-wash-and-auto-services', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 29, 'name' => 'Repair & Maintenance', 'icon' => 'fas fa-tools', 'color' => '#F59E0B', 'order' => 29, 'active' => 1, 'parent_id' => 27, 'description' => 'Repair & Maintenance offers and deals in the UAE.', 'slug' => 'repair-and-maintenance', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 30, 'name' => 'Home Services', 'icon' => 'fas fa-tools', 'color' => '#F59E0B', 'order' => 30, 'active' => 1, 'parent_id' => 27, 'description' => 'Home Services offers and deals in the UAE.', 'slug' => 'home-services', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 31, 'name' => 'Printing & Advertising', 'icon' => 'fas fa-tools', 'color' => '#F59E0B', 'order' => 31, 'active' => 1, 'parent_id' => 27, 'description' => 'Printing & Advertising offers and deals in the UAE.', 'slug' => 'printing-and-advertising', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 32, 'name' => 'Courses & Educational Workshops', 'icon' => 'fas fa-tools', 'color' => '#F59E0B', 'order' => 32, 'active' => 1, 'parent_id' => 27, 'description' => 'Courses & Educational Workshops offers and deals in the UAE.', 'slug' => 'courses-and-educational-workshops', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 33, 'name' => 'Translation & Freelance Services', 'icon' => 'fas fa-tools', 'color' => '#F59E0B', 'order' => 33, 'active' => 1, 'parent_id' => 27, 'description' => 'Translation & Freelance Services offers and deals in the UAE.', 'slug' => 'translation-and-freelance-services', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 34, 'name' => 'Special & Seasonal Offers', 'icon' => 'fas fa-gift', 'color' => '#EF4444', 'order' => 34, 'active' => 1, 'parent_id' => null, 'description' => 'Special & Seasonal Offers related offers and discounts.', 'slug' => 'special-and-seasonal-offers', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 35, 'name' => 'Ramadan Deals', 'icon' => 'fas fa-gift', 'color' => '#EF4444', 'order' => 35, 'active' => 1, 'parent_id' => 34, 'description' => 'Ramadan Deals offers and deals in the UAE.', 'slug' => 'ramadan-deals', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 36, 'name' => 'Weekend Offers', 'icon' => 'fas fa-gift', 'color' => '#EF4444', 'order' => 36, 'active' => 1, 'parent_id' => 34, 'description' => 'Weekend Offers offers and deals in the UAE.', 'slug' => 'weekend-offers', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 37, 'name' => 'Black Friday Deals', 'icon' => 'fas fa-gift', 'color' => '#EF4444', 'order' => 37, 'active' => 1, 'parent_id' => 34, 'description' => 'Black Friday Deals offers and deals in the UAE.', 'slug' => 'black-friday-deals', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 38, 'name' => 'End-of-Season Sales', 'icon' => 'fas fa-gift', 'color' => '#EF4444', 'order' => 38, 'active' => 1, 'parent_id' => 34, 'description' => 'End-of-Season Sales offers and deals in the UAE.', 'slug' => 'end-of-season-sales', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 39, 'name' => 'Grand Opening Offers', 'icon' => 'fas fa-gift', 'color' => '#EF4444', 'order' => 39, 'active' => 1, 'parent_id' => 34, 'description' => 'Grand Opening Offers offers and deals in the UAE.', 'slug' => 'grand-opening-offers', 'created_at' => $now, 'updated_at' => $now],
        ];

        foreach ($categories as $category) {
            OfferCategory::create($category);
        }
    }
} 